const FETCH_TASKS_START = "FETCH_TASKS_START";
const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
const FETCH_TASKS_FAIL = "FETCH_TASKS_FAIL";

const TOGGLE_TASK = "TOGGLE_TASK";


export {
  FETCH_TASKS_START,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_FAIL,
  TOGGLE_TASK,
};
