const FETCH_TASKS_START = "FETCH_TASKS_START";
const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
const FETCH_TASKS_FAIL = "FETCH_TASKS_FAIL";
const SHOW_ALL_GROUPS = "SHOW_ALL_GROUPS";
const SHOW_TASK_GROUP = "SHOW_TASK_GROUP";

const TOGGLE_TASK = "TOGGLE_TASK";


export {
  FETCH_TASKS_START,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_FAIL,
  SHOW_ALL_GROUPS,
  SHOW_TASK_GROUP,
  TOGGLE_TASK,
};
